# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from substrate_237.cross_platform_consensus import consensus_protocol_pb2 as substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in substrate_237/cross_platform_consensus/consensus_protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedConsensusServiceStub(object):
    """=== Serviço gRPC para consenso federado ===

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitProposal = channel.unary_unary(
                '/arkhe.consensus.v1.FederatedConsensusService/SubmitProposal',
                request_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitProposalRequest.SerializeToString,
                response_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitProposalResponse.FromString,
                _registered_method=True)
        self.SubmitVote = channel.unary_unary(
                '/arkhe.consensus.v1.FederatedConsensusService/SubmitVote',
                request_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitVoteRequest.SerializeToString,
                response_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitVoteResponse.FromString,
                _registered_method=True)
        self.GetConsensusStatus = channel.unary_unary(
                '/arkhe.consensus.v1.FederatedConsensusService/GetConsensusStatus',
                request_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.GetConsensusStatusRequest.SerializeToString,
                response_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.GetConsensusStatusResponse.FromString,
                _registered_method=True)
        self.RegisterOrganization = channel.unary_unary(
                '/arkhe.consensus.v1.FederatedConsensusService/RegisterOrganization',
                request_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.RegisterOrganizationRequest.SerializeToString,
                response_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.RegisterOrganizationResponse.FromString,
                _registered_method=True)
        self.StreamConsensusUpdates = channel.unary_stream(
                '/arkhe.consensus.v1.FederatedConsensusService/StreamConsensusUpdates',
                request_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.StreamUpdatesRequest.SerializeToString,
                response_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.ConsensusUpdate.FromString,
                _registered_method=True)


class FederatedConsensusServiceServicer(object):
    """=== Serviço gRPC para consenso federado ===

    """

    def SubmitProposal(self, request, context):
        """Submeter nova proposta para consenso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitVote(self, request, context):
        """Votar em proposta ativa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsensusStatus(self, request, context):
        """Consultar status de consenso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterOrganization(self, request, context):
        """Registrar identidade da organização no consenso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConsensusUpdates(self, request, context):
        """Stream de atualizações de consenso em tempo real
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitProposal,
                    request_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitProposalRequest.FromString,
                    response_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitProposalResponse.SerializeToString,
            ),
            'SubmitVote': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitVote,
                    request_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitVoteRequest.FromString,
                    response_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitVoteResponse.SerializeToString,
            ),
            'GetConsensusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsensusStatus,
                    request_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.GetConsensusStatusRequest.FromString,
                    response_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.GetConsensusStatusResponse.SerializeToString,
            ),
            'RegisterOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterOrganization,
                    request_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.RegisterOrganizationRequest.FromString,
                    response_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.RegisterOrganizationResponse.SerializeToString,
            ),
            'StreamConsensusUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConsensusUpdates,
                    request_deserializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.StreamUpdatesRequest.FromString,
                    response_serializer=substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.ConsensusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arkhe.consensus.v1.FederatedConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arkhe.consensus.v1.FederatedConsensusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedConsensusService(object):
    """=== Serviço gRPC para consenso federado ===

    """

    @staticmethod
    def SubmitProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.consensus.v1.FederatedConsensusService/SubmitProposal',
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitProposalRequest.SerializeToString,
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.consensus.v1.FederatedConsensusService/SubmitVote',
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitVoteRequest.SerializeToString,
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.SubmitVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsensusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.consensus.v1.FederatedConsensusService/GetConsensusStatus',
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.GetConsensusStatusRequest.SerializeToString,
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.GetConsensusStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.consensus.v1.FederatedConsensusService/RegisterOrganization',
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.RegisterOrganizationRequest.SerializeToString,
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.RegisterOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConsensusUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arkhe.consensus.v1.FederatedConsensusService/StreamConsensusUpdates',
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.StreamUpdatesRequest.SerializeToString,
            substrate__237_dot_cross__platform__consensus_dot_consensus__protocol__pb2.ConsensusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
