/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ARKHERoyaltyEscrow {
  export type EscrowConfigStruct = {
    defaultReleaseDelay: BigNumberish;
    defaultExpiryDelay: BigNumberish;
    minDeposit: BigNumberish;
    maxDeposit: BigNumberish;
    disputeResolver: AddressLike;
    protocolTreasury: AddressLike;
  };

  export type EscrowConfigStructOutput = [
    defaultReleaseDelay: bigint,
    defaultExpiryDelay: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    disputeResolver: string,
    protocolTreasury: string
  ] & {
    defaultReleaseDelay: bigint;
    defaultExpiryDelay: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    disputeResolver: string;
    protocolTreasury: string;
  };

  export type BatchDepositParamsStruct = {
    beneficiary: AddressLike;
    tokenAddress: AddressLike;
    amount: BigNumberish;
    expiryDelay: BigNumberish;
  };

  export type BatchDepositParamsStructOutput = [
    beneficiary: string,
    tokenAddress: string,
    amount: bigint,
    expiryDelay: bigint
  ] & {
    beneficiary: string;
    tokenAddress: string;
    amount: bigint;
    expiryDelay: bigint;
  };
}

export interface ARKHERoyaltyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchDeposit"
      | "batchRelease"
      | "batchSubmitProof"
      | "config"
      | "createDeposit"
      | "deposits"
      | "depositsByBeneficiary"
      | "depositsByDepositor"
      | "emergencyRefund"
      | "getDepositCount"
      | "getDepositsByBeneficiary"
      | "isRefundable"
      | "isReleasable"
      | "refund"
      | "release"
      | "resolveDispute"
      | "submitProof"
      | "totalDeposits"
      | "totalRefunded"
      | "totalReleased"
      | "updateConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchDeposited"
      | "BatchReleased"
      | "ConfigUpdated"
      | "DepositCreated"
      | "DisputeResolverUpdated"
      | "EmergencyWithdrawal"
      | "ProofSubmitted"
      | "Refunded"
      | "Released"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchDeposit",
    values: [ARKHERoyaltyEscrow.BatchDepositParamsStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRelease",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSubmitProof",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createDeposit",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposits", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "depositsByBeneficiary",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositsByDepositor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositsByBeneficiary",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRefundable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isReleasable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRefunded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSubmitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositsByBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositsByDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositsByBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRefundable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReleasable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRefunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
}

export namespace BatchDepositedEvent {
  export type InputTuple = [count: BigNumberish, depositIds: BytesLike[]];
  export type OutputTuple = [count: bigint, depositIds: string[]];
  export interface OutputObject {
    count: bigint;
    depositIds: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchReleasedEvent {
  export type InputTuple = [count: BigNumberish, depositIds: BytesLike[]];
  export type OutputTuple = [count: bigint, depositIds: string[]];
  export interface OutputObject {
    count: bigint;
    depositIds: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [
    updater: AddressLike,
    field: BigNumberish,
    newValue: BigNumberish
  ];
  export type OutputTuple = [updater: string, field: bigint, newValue: bigint];
  export interface OutputObject {
    updater: string;
    field: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositCreatedEvent {
  export type InputTuple = [
    depositId: BytesLike,
    depositor: AddressLike,
    beneficiary: AddressLike,
    amount: BigNumberish,
    token: AddressLike,
    releaseTime: BigNumberish,
    expiryTime: BigNumberish
  ];
  export type OutputTuple = [
    depositId: string,
    depositor: string,
    beneficiary: string,
    amount: bigint,
    token: string,
    releaseTime: bigint,
    expiryTime: bigint
  ];
  export interface OutputObject {
    depositId: string;
    depositor: string;
    beneficiary: string;
    amount: bigint;
    token: string;
    releaseTime: bigint;
    expiryTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolverUpdatedEvent {
  export type InputTuple = [old: AddressLike, new_: AddressLike];
  export type OutputTuple = [old: string, new_: string];
  export interface OutputObject {
    old: string;
    new_: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [depositId: BytesLike, proofHash: BytesLike];
  export type OutputTuple = [depositId: string, proofHash: string];
  export interface OutputObject {
    depositId: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    depositId: BytesLike,
    depositor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    depositId: string,
    depositor: string,
    amount: bigint
  ];
  export interface OutputObject {
    depositId: string;
    depositor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    depositId: BytesLike,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    depositId: string,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    depositId: string;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ARKHERoyaltyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ARKHERoyaltyEscrow;
  waitForDeployment(): Promise<this>;

  interface: ARKHERoyaltyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchDeposit: TypedContractMethod<
    [params: ARKHERoyaltyEscrow.BatchDepositParamsStruct[]],
    [string[]],
    "payable"
  >;

  batchRelease: TypedContractMethod<
    [depositIds: BytesLike[]],
    [void],
    "nonpayable"
  >;

  batchSubmitProof: TypedContractMethod<
    [depositIds: BytesLike[], proofHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  config: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, string, string] & {
        defaultReleaseDelay: bigint;
        defaultExpiryDelay: bigint;
        minDeposit: bigint;
        maxDeposit: bigint;
        disputeResolver: string;
        protocolTreasury: string;
      }
    ],
    "view"
  >;

  createDeposit: TypedContractMethod<
    [
      beneficiary: AddressLike,
      tokenAddress: AddressLike,
      expiryDelayOverride: BigNumberish
    ],
    [string],
    "payable"
  >;

  deposits: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        depositId: string;
        depositor: string;
        beneficiary: string;
        amount: bigint;
        createdAt: bigint;
        releaseTime: bigint;
        expiryTime: bigint;
        proofHash: string;
        proofSubmitted: boolean;
        released: boolean;
        refunded: boolean;
        tokenAddress: string;
      }
    ],
    "view"
  >;

  depositsByBeneficiary: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  depositsByDepositor: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  emergencyRefund: TypedContractMethod<
    [depositId: BytesLike],
    [void],
    "nonpayable"
  >;

  getDepositCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getDepositsByBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  isRefundable: TypedContractMethod<[depositId: BytesLike], [boolean], "view">;

  isReleasable: TypedContractMethod<[depositId: BytesLike], [boolean], "view">;

  refund: TypedContractMethod<[depositId: BytesLike], [void], "nonpayable">;

  release: TypedContractMethod<[depositId: BytesLike], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [depositId: BytesLike, releaseToBeneficiary: boolean],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [depositId: BytesLike, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  totalDeposits: TypedContractMethod<[], [bigint], "view">;

  totalRefunded: TypedContractMethod<[], [bigint], "view">;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  updateConfig: TypedContractMethod<
    [field: BigNumberish, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchDeposit"
  ): TypedContractMethod<
    [params: ARKHERoyaltyEscrow.BatchDepositParamsStruct[]],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "batchRelease"
  ): TypedContractMethod<[depositIds: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchSubmitProof"
  ): TypedContractMethod<
    [depositIds: BytesLike[], proofHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, string, string] & {
        defaultReleaseDelay: bigint;
        defaultExpiryDelay: bigint;
        minDeposit: bigint;
        maxDeposit: bigint;
        disputeResolver: string;
        protocolTreasury: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createDeposit"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      tokenAddress: AddressLike,
      expiryDelayOverride: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        depositId: string;
        depositor: string;
        beneficiary: string;
        amount: bigint;
        createdAt: bigint;
        releaseTime: bigint;
        expiryTime: bigint;
        proofHash: string;
        proofSubmitted: boolean;
        released: boolean;
        refunded: boolean;
        tokenAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositsByBeneficiary"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositsByDepositor"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyRefund"
  ): TypedContractMethod<[depositId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDepositCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDepositsByBeneficiary"
  ): TypedContractMethod<
    [beneficiary: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRefundable"
  ): TypedContractMethod<[depositId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isReleasable"
  ): TypedContractMethod<[depositId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[depositId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[depositId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [depositId: BytesLike, releaseToBeneficiary: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [depositId: BytesLike, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalDeposits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRefunded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateConfig"
  ): TypedContractMethod<
    [field: BigNumberish, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchDeposited"
  ): TypedContractEvent<
    BatchDepositedEvent.InputTuple,
    BatchDepositedEvent.OutputTuple,
    BatchDepositedEvent.OutputObject
  >;
  getEvent(
    key: "BatchReleased"
  ): TypedContractEvent<
    BatchReleasedEvent.InputTuple,
    BatchReleasedEvent.OutputTuple,
    BatchReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositCreated"
  ): TypedContractEvent<
    DepositCreatedEvent.InputTuple,
    DepositCreatedEvent.OutputTuple,
    DepositCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolverUpdated"
  ): TypedContractEvent<
    DisputeResolverUpdatedEvent.InputTuple,
    DisputeResolverUpdatedEvent.OutputTuple,
    DisputeResolverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;

  filters: {
    "BatchDeposited(uint256,bytes32[])": TypedContractEvent<
      BatchDepositedEvent.InputTuple,
      BatchDepositedEvent.OutputTuple,
      BatchDepositedEvent.OutputObject
    >;
    BatchDeposited: TypedContractEvent<
      BatchDepositedEvent.InputTuple,
      BatchDepositedEvent.OutputTuple,
      BatchDepositedEvent.OutputObject
    >;

    "BatchReleased(uint256,bytes32[])": TypedContractEvent<
      BatchReleasedEvent.InputTuple,
      BatchReleasedEvent.OutputTuple,
      BatchReleasedEvent.OutputObject
    >;
    BatchReleased: TypedContractEvent<
      BatchReleasedEvent.InputTuple,
      BatchReleasedEvent.OutputTuple,
      BatchReleasedEvent.OutputObject
    >;

    "ConfigUpdated(address,uint8,uint256)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "DepositCreated(bytes32,address,address,uint256,address,uint256,uint256)": TypedContractEvent<
      DepositCreatedEvent.InputTuple,
      DepositCreatedEvent.OutputTuple,
      DepositCreatedEvent.OutputObject
    >;
    DepositCreated: TypedContractEvent<
      DepositCreatedEvent.InputTuple,
      DepositCreatedEvent.OutputTuple,
      DepositCreatedEvent.OutputObject
    >;

    "DisputeResolverUpdated(address,address)": TypedContractEvent<
      DisputeResolverUpdatedEvent.InputTuple,
      DisputeResolverUpdatedEvent.OutputTuple,
      DisputeResolverUpdatedEvent.OutputObject
    >;
    DisputeResolverUpdated: TypedContractEvent<
      DisputeResolverUpdatedEvent.InputTuple,
      DisputeResolverUpdatedEvent.OutputTuple,
      DisputeResolverUpdatedEvent.OutputObject
    >;

    "EmergencyWithdrawal(address,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "ProofSubmitted(bytes32,bytes32)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "Refunded(bytes32,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Released(bytes32,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
  };
}
