from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, PlainTextResponse
import uvicorn
import yaml
import json

app = FastAPI(title="ARKHE-Z Bridge Server")

@app.post("/api/v1/bridge/publish")
async def publish_bridge(request: Request):
    try:
        data = await request.json()
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON")

    # Process the bridge publication
    # Simulating processing

    decree = {
        "decree_type": "BRIDGE_PUBLISH",
        "status": "CANONIZED",
        "description": "Bridge execution decree generated by server",
        "input_data": data
    }

    format_type = request.query_params.get("format", "json")
    if format_type == "yaml":
        return PlainTextResponse(yaml.dump(decree), media_type="application/x-yaml")

    return JSONResponse(content=decree)

@app.post("/api/v1/bridge/verify")
async def verify_bridge(request: Request):
    try:
        data = await request.json()
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON")

    # Verify the hash or data
    provided_hash = data.get("hash")

    result = {
        "decree_type": "BRIDGE_VERIFY",
        "status": "VERIFIED",
        "valid": True,
        "hash": provided_hash
    }

    format_type = request.query_params.get("format", "json")
    if format_type == "yaml":
        return PlainTextResponse(yaml.dump(result), media_type="application/x-yaml")

    return JSONResponse(content=result)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
