#!/usr/bin/env python3
"""
export_to_lumerical.py
Exports vortex array model to Lumerical FDTD format for full-wave electromagnetic simulation.
"""
import numpy as np
import json
from pathlib import Path

# Provide a mock VORTEX_PARAMS since we can't reliably import it if it's missing from the simulate module script we checked
VORTEX_PARAMS = {
    'array_size': (10, 10),
    'pitch': 1e-6,
    'wavelength_range': (400e-9, 1550e-9),
    'n_pixels': 1151,
    'depth': 1.5e-6,
    'core_diameter': 300e-9,
    'dn_range': (0.02, 0.08)
}

def generate_lumerical_script(vortex_params, output_path='exports/vortex_array_lumerical.lsf'):
    script = f"""# ARKHE Micro-Vortex Array - Lumerical FDTD Simulation
# Generated by ARKHE OS v∞.340.2
# Date: {np.datetime64('now')}

# === Simulation Setup ===
addfdtd;
set("name", "ARKHE_Vortex_Simulation");
set("x span", {vortex_params['array_size'][0] * vortex_params['pitch'] * 1e6 + 2});  # μm
set("y span", {vortex_params['array_size'][1] * vortex_params['pitch'] * 1e6 + 2});
set("z span", 5);  # Sufficient for far-field
set("mesh accuracy", 3);  # High accuracy for sub-wavelength features

# === Material: PMMA with laser-induced index modulation ===
addmaterial("PMMA_laser_modified");
set("name", "PMMA_modified");
set("index", 1.49);  # Base index
# Note: Spatial index modulation defined via import below

# === Vortex Array Geometry ===
# Import refractive index profile from numpy file
n_profile_file = "{Path('exports/vortex_index_profile.npy').resolve()}";
importnprofile(n_profile_file);

# === Source: Broadband plane wave ===
addplane;
set("name", "broadband_source");
set("wavelength start", {vortex_params['wavelength_range'][0] * 1e9});  # nm
set("wavelength stop", {vortex_params['wavelength_range'][1] * 1e9});
set("theta", 0);
set("phi", 0);
set("injection axis", "z");

# === Monitors ===
# Far-field monitor for spectral response
addfarfield;
set("name", "farfield_spectrum");
set("monitor type", "far field");
set("wavelength start", {vortex_params['wavelength_range'][0] * 1e9});
set("wavelength stop", {vortex_params['wavelength_range'][1] * 1e9});
set("wavelength points", {vortex_params['n_pixels']});

# Near-field monitor for phase verification
addprofile;
set("name", "nearfield_phase");
set("monitor type", "2D Z-normal");
set("x", 0);
set("y", 0);
set("z", {vortex_params['depth'] * 1e6 + 0.5});

# === Simulation Execution ===
run;

# === Post-processing: Extract spectral response ===
# Calculate intensity vs wavelength from far-field monitor
lambda_axis = getdata("farfield_spectrum", "wavelength");
intensity = getdata("farfield_spectrum", "farfield3d");
spectral_response = mean(abs(intensity)^2, 3);  # Average over angles

# Export results
export("spectral_response.csv", lambda_axis', spectral_response');

echo("Simulation complete. Results exported to spectral_response.csv");
"""

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(script)

    print(f"✓ Lumerical script saved: {output_path}")
    return output_path

def generate_index_profile_npy(vortex_params, output_path='exports/vortex_index_profile.npy'):
    print(f"🔧 Generating refractive index profile: {output_path}")

    nx, ny = 128, 128
    x = np.linspace(-6e-6, 6e-6, nx)
    y = np.linspace(-6e-6, 6e-6, ny)
    X, Y = np.meshgrid(x, y)

    n_base = 1.49
    n_profile = np.ones_like(X) * n_base

    pitch = vortex_params['pitch']
    core_d = vortex_params['core_diameter']
    dn_mean = np.mean(vortex_params['dn_range'])

    for i in range(vortex_params['array_size'][0]):
        for j in range(vortex_params['array_size'][1]):
            cx = (i - vortex_params['array_size'][0]/2 + 0.5) * pitch
            cy = (j - vortex_params['array_size'][1]/2 + 0.5) * pitch

            r = np.sqrt((X - cx)**2 + (Y - cy)**2)
            theta = np.arctan2(Y - cy, X - cx)

            radial = np.exp(-((r - core_d/2)**2) / (2 * (core_d/4)**2))
            phase_mod = np.cos(theta) * radial

            n_profile += dn_mean * phase_mod

    export_data = np.stack([X.flatten(), Y.flatten(), n_profile.flatten()], axis=1)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    np.save(output_path, export_data)

    print(f"✓ Index profile saved: {output_path}")
    return output_path

if __name__ == '__main__':
    generate_index_profile_npy(VORTEX_PARAMS)
    generate_lumerical_script(VORTEX_PARAMS)

    print(f"\n✅ Export to Lumerical complete")
    print(f"🔗 Files ready:")
    print(f"   • exports/vortex_index_profile.npy")
    print(f"   • exports/vortex_array_lumerical.lsf")
