[pytest]
asyncio_default_fixture_loop_scope = function
markers =
    e2e: marks tests as e2e (deselect with '-m "not e2e"')
    slow: marks tests as slow (deselect with '-m "not slow"')
    fast: marks tests as fast (deselect with '-m "not fast"')
