// arkhe_os/integration/kernel_integration_orchestrator.go
package integration

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"time"

	"arkhe/ai"
	"arkhe/parser/frontends"
)

// IntegrationEvent represents an event generated by the orchestrator.
type IntegrationEvent struct {
	EventType string
	ClusterID string
	Data      map[string]interface{}
	Timestamp time.Time
}

// IntegrationMetrics represents metrics for the orchestrator.
type IntegrationMetrics struct {
	ScansCompleted   int64
	FilesScanned     int64
	GraphsProcessed  int64
	CoherenceMetrics *MapperMetrics
}

// KernelIntegrationOrchestrator orquestra parsing de kernel → LFIR → Coerência
type KernelIntegrationOrchestrator struct {
	mu sync.RWMutex

	// Componentes
	kernelParser    *frontends.KernelFrontend
	coherenceMapper *KernelCoherenceMapper

	// Configuração
	config KernelIntegrationConfig

	// Estado
	kernelVersion  string
	kernelArch     string
	monitorPaths   []string // Diretórios para monitorar (src, configs)
	commandPollers map[string]*exec.Cmd
	lastScanTime   time.Time
	scanInterval   time.Duration

	// Métricas
	metrics IntegrationMetrics

	// Callbacks
	integrationCallbacks []func(IntegrationEvent)
}

// KernelIntegrationConfig contém configuração para integração de kernel
type KernelIntegrationConfig struct {
	ScanIntervalSec       int64
	EnableCoherenceMap    bool
	EnableAutoPromotion   bool // Promover kernels com alta coerência estrutural
	CoherenceThreshold    float64
	MonitorSourcePaths    []string // Caminhos para código-fonte do kernel
	MonitorConfigPaths    []string // Caminhos para .config, Kconfig
	PollKallsyms          bool     // Poll /proc/kallsyms periodicamente
	PollLsmod             bool     // Poll lsmod periodicamente
	PollCmdline           bool     // Poll /proc/cmdline periodicamente
}

// NewKernelIntegrationOrchestrator cria novo orquestrador de integração de kernel
func NewKernelIntegrationOrchestrator(
	version, arch string,
	config KernelIntegrationConfig,
	gradientChannel *ai.CoherenceGradientChannel,
) (*KernelIntegrationOrchestrator, error) {
	if config.ScanIntervalSec == 0 {
		config.ScanIntervalSec = 600 // 10 minutos padrão (kernel muda menos frequentemente)
	}
	if config.CoherenceThreshold == 0 {
		config.CoherenceThreshold = 0.80 // Kernel requer coerência mais alta
	}

	orch := &KernelIntegrationOrchestrator{
		kernelVersion:  version,
		kernelArch:     arch,
		config:         config,
		monitorPaths:   append(config.MonitorSourcePaths, config.MonitorConfigPaths...),
		commandPollers: make(map[string]*exec.Cmd),
		scanInterval:   time.Duration(config.ScanIntervalSec) * time.Second,
	}

	// Inicializar parser de kernel
	parser, _ := frontends.NewKernelFrontend(version, arch)
	orch.kernelParser = parser

	// Inicializar mapeador de coerência se habilitado
	if config.EnableCoherenceMap && gradientChannel != nil {
		orch.coherenceMapper = NewKernelCoherenceMapper(
			KernelCoherenceConfig{
				EnableAutoSubmission: true,
				SyscallWeightSuccess: 0.03,
				ModuleWeightHealthy:  0.02,
				MinCoherenceDelta:    0.01,
				CriticalityThreshold: 0.7,
			},
			gradientChannel,
		)
	}

	return orch, nil
}

// ScanKernelFiles executa scan de arquivos de kernel
func (orch *KernelIntegrationOrchestrator) ScanKernelFiles(ctx context.Context) error {
	orch.mu.Lock()
	orch.lastScanTime = time.Now()
	orch.mu.Unlock()

	filesScanned := 0
	graphsProcessed := 0

	// Scan de arquivos de código e configuração
	for _, path := range orch.monitorPaths {
		info, err := os.Stat(path)
		if err != nil {
			continue
		}

		var files []string
		if info.IsDir() {
			// Listar arquivos relevantes no diretório
			err := filepath.Walk(path, func(filePath string, info os.FileInfo, err error) error {
				if err != nil {
					return nil
				}
				ext := filepath.Ext(filePath)
				base := filepath.Base(filePath)
				if ext == ".c" || ext == ".h" || base == ".config" || base == "Kconfig" ||
					base == "kallsyms" || base == "cmdline" {
					files = append(files, filePath)
				}
				return nil
			})
			if err != nil {
				continue
			}
		} else {
			files = []string{path}
		}

		for _, file := range files {
			content, err := os.ReadFile(file)
			if err != nil {
				continue
			}

			graph, err := orch.kernelParser.Parse(content)
			if err != nil {
				continue
			}

			filesScanned++
			graphsProcessed++

			if orch.coherenceMapper != nil {
				if err := orch.coherenceMapper.ProcessLFIRGraph(graph); err != nil {
					// Logar erro mas não falhar o scan
				}
			}
		}
	}

	// Poll /proc/kallsyms se habilitado
	if orch.config.PollKallsyms {
		if output, err := exec.CommandContext(ctx, "cat", "/proc/kallsyms").Output(); err == nil {
			graph, err := orch.kernelParser.Parse(output)
			if err == nil {
				graphsProcessed++
				if orch.coherenceMapper != nil {
					orch.coherenceMapper.ProcessLFIRGraph(graph)
				}
			}
		}
	}

	// Poll lsmod se habilitado
	if orch.config.PollLsmod {
		if output, err := exec.CommandContext(ctx, "lsmod").Output(); err == nil {
			graph, err := orch.kernelParser.Parse(output)
			if err == nil {
				graphsProcessed++
				if orch.coherenceMapper != nil {
					orch.coherenceMapper.ProcessLFIRGraph(graph)
				}
			}
		}
	}

	// Poll /proc/cmdline se habilitado
	if orch.config.PollCmdline {
		if output, err := exec.CommandContext(ctx, "cat", "/proc/cmdline").Output(); err == nil {
			graph, err := orch.kernelParser.Parse(output)
			if err == nil {
				graphsProcessed++
				if orch.coherenceMapper != nil {
					orch.coherenceMapper.ProcessLFIRGraph(graph)
				}
			}
		}
	}

	// Atualizar métricas
	orch.mu.Lock()
	orch.metrics.ScansCompleted++
	orch.metrics.FilesScanned += int64(filesScanned)
	orch.metrics.GraphsProcessed += int64(graphsProcessed)
	orch.mu.Unlock()

	// Notificar callbacks
	orch.mu.RLock()
	callbacks := make([]func(IntegrationEvent), len(orch.integrationCallbacks))
	copy(callbacks, orch.integrationCallbacks)
	orch.mu.RUnlock()

	for _, cb := range callbacks {
		cb(IntegrationEvent{
			EventType: "kernel_scan_completed",
			ClusterID: fmt.Sprintf("kernel-%s-%s", orch.kernelVersion, orch.kernelArch),
			Data: map[string]interface{}{
				"files_scanned":    filesScanned,
				"graphs_processed": graphsProcessed,
				"scan_time":        orch.lastScanTime,
				"version":          orch.kernelVersion,
				"arch":             orch.kernelArch,
			},
			Timestamp: time.Now(),
		})
	}

	return nil
}

// StartContinuousScanning inicia loop de scan contínuo de kernel
func (orch *KernelIntegrationOrchestrator) StartContinuousScanning(ctx context.Context) {
	ticker := time.NewTicker(orch.scanInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			if err := orch.ScanKernelFiles(ctx); err != nil {
				// Logar erro mas continuar loop
				continue
			}
		}
	}
}

// GetIntegrationMetrics retorna métricas consolidadas da integração de kernel
func (orch *KernelIntegrationOrchestrator) GetIntegrationMetrics() IntegrationMetrics {
	orch.mu.RLock()
	defer orch.mu.RUnlock()

	if orch.coherenceMapper != nil {
		mapperMetrics := orch.coherenceMapper.GetMapperMetrics()
		orch.metrics.CoherenceMetrics = &mapperMetrics
	}

	return orch.metrics
}

// RegisterIntegrationCallback registra callback para eventos de integração
func (orch *KernelIntegrationOrchestrator) RegisterIntegrationCallback(
	cb func(IntegrationEvent),
) {
	orch.mu.Lock()
	defer orch.mu.Unlock()
	orch.integrationCallbacks = append(orch.integrationCallbacks, cb)
}
