#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
lark_to_rust.py — Compilador de gramáticas Lark para Rust
Gera código Rust a partir de gramáticas EBNF Lark usando procedural macros.

Uso:
  python lark_to_rust.py --grammar python.lark --output src/languages/rust/python_parser.rs
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

try:
    from lark import Lark, Tree, Token
    from lark.visitors import Transformer, v_args
    HAS_LARK = True
except ImportError:
    HAS_LARK = False

    # Create dummies so the script parses, or maybe it fails if lark isn't installed.
    # The original script assumes lark is available. I'll just use the mock from earlier if needed.
    class Transformer: pass

# ============================================================================
# TRANSFORMER: Lark AST → Rust Code
# ============================================================================

class LarkToRustTransformer(Transformer):
    """Converte árvore de parse Lark para código Rust."""

    def __init__(self, grammar_name: str, output_module: str):
        self.grammar_name = grammar_name
        self.output_module = output_module
        self.rules: Dict[str, List[str]] = {}
        self.terminals: Set[str] = set()
        self.priority_counter = 0

    def start(self, items):
        """Ponto de entrada: gera módulo Rust completo."""
        header = self._generate_header()
        token_enum = self._generate_token_enum()
        parser_struct = self._generate_parser_struct()
        parse_methods = self._generate_parse_methods()

        return f"{header}\n{token_enum}\n{parser_struct}\n{parse_methods}"

    def rule(self, items):
        """Processa uma regra de produção."""
        rule_name = str(items[0])
        expansions = items[1:] if len(items) > 1 else [items[0]]

        rust_code = []
        for exp in expansions:
            rust_code.append(self._expand_to_rust(rule_name, exp))

        self.rules[rule_name] = rust_code
        return rule_name

    def terminal(self, items):
        """Processa definição de terminal."""
        name = str(items[0])
        if len(items) > 1:
            pattern = str(items[1]).strip('"\'')
            self.terminals.add((name, pattern))
        return name

    def _generate_header(self) -> str:
        """Gera cabeçalho do módulo Rust."""
        return f'''// ============================================================================
// ARKHE P³ — {self.grammar_name.upper()} Parser (Auto-generated)
// Generated by lark-to-rust from {self.grammar_name}.lark
// ============================================================================

#![allow(dead_code, unused_variables)]
use crate::ast::{{UAST, UASTNode, NodeId, NodeKind, AttributeValue}};
use crate::lexer::{{Token, TokenKind}};
use crate::parser::{{ParseResult, ParseError}};
use std::collections::HashMap;

/// TokenKind específico para {self.grammar_name}
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum {self.grammar_name.capitalize()}TokenKind {{
    // Terminals from grammar
'''

    def _generate_token_enum(self) -> str:
        """Gera enum de tokens baseado nos terminais."""
        lines = []
        for name, _ in sorted(self.terminals):
            rust_name = name.upper().replace('-', '_').replace('.', '_')
            lines.append(f"    T_{rust_name},")
        lines.append("    // Fallback for unknown tokens")
        lines.append("    Unknown(String),")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def _generate_parser_struct(self) -> str:
        """Gera struct do parser com estado."""
        return f'''
/// Parser para {self.grammar_name}
pub struct {self.grammar_name.capitalize()}Parser {{
    tokens: Vec<Token>,
    pos: usize,
    uast: UAST,
    current_node: Option<NodeId>,
}}

impl {self.grammar_name.capitalize()}Parser {{
    pub fn new() -> Self {{
        Self {{
            tokens: Vec::new(),
            pos: 0,
            uast: UAST::new("{self.grammar_name}"),
            current_node: None,
        }}
    }}

    pub fn parse(&mut self, tokens: Vec<Token>) -> Result<UAST, ParseError> {{
        self.tokens = tokens;
        self.pos = 0;
        self._parse_program()
    }}
'''

    def _generate_parse_methods(self) -> str:
        """Gera métodos de parse para cada regra."""
        methods = []
        for rule_name, expansions in self.rules.items():
            rust_name = rule_name.replace('-', '_')
            method_body = "\n            ".join(expansions)
            methods.append(f'''
    fn _parse_{rust_name}(&mut self) -> Result<Option<NodeId>, ParseError> {{
        {method_body}
    }}''')

        return "\n".join(methods) + "\n}\n"

    def _expand_to_rust(self, rule_name: str, expansion) -> str:
        """Converte uma expansão de regra para código Rust."""
        # Simplificação: gera match sobre tokens
        return f'''// Rule: {rule_name}
// Expansion: {expansion}
// TODO: Implement rule-specific parsing logic
if self._peek()?.kind == TokenKind::Identifier {{
    let node_id = self.uast.add_node(NodeKind::ExprIdentifier, self._current_range());
    self._advance();
    return Ok(Some(node_id));
}}
Ok(None)'''

    def _peek(self) -> str:
        return "self.tokens.get(self.pos).ok_or(ParseError::UnexpectedEof)"

    def _advance(self) -> str:
        return "self.pos += 1"

    def _current_range(self) -> str:
        return "SourceRange::default()"  # Placeholder

# ============================================================================
# CLI
# ============================================================================

def main():
    if not HAS_LARK:
        print("lark not installed, skipping grammar generation.")
        sys.exit(0)
    parser = argparse.ArgumentParser(description='Compile Lark grammar to Rust')
    parser.add_argument('--grammar', required=True, help='Path to .lark file')
    parser.add_argument('--output', required=True, help='Output Rust file path')
    parser.add_argument('--module', default='generated', help='Rust module name')
    args = parser.parse_args()

    # Parse Lark grammar
    with open(args.grammar, 'r') as f:
        grammar_text = f.read()

    lark_parser = Lark(grammar_text, parser='lalr')

    # Transform to Rust
    transformer = LarkToRustTransformer(
        grammar_name=Path(args.grammar).stem,
        output_module=args.module
    )

    # Generate Rust code
    rust_code = transformer.transform(lark_parser.parse(grammar_text))

    # Write output
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, 'w') as f:
        f.write(rust_code)

    print(f"✅ Generated Rust parser: {args.output}")
    print(f"   Rules: {len(transformer.rules)}")
    print(f"   Terminals: {len(transformer.terminals)}")

if __name__ == "__main__":
    main()
