apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: arkhe-server-network-policy
spec:
  podSelector:
    matchLabels:
      app: arkhe-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
