// arkhe_ioctl.h — Interface entre o Mundo e o Kernel

#define ARKHE_DEVICE_NAME L"\\Device\\Arkhe"
#define ARKHE_SYMBOLIC_NAME L"\\DosDevices\\Arkhe"

#define IOCTL_ARKHE_QUERY_STATUS    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARKHE_SUBMIT_EVENT    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARKHE_GET_VERDICT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARKHE_SYNC_K6O        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _ARKHE_STATUS {
    ULONG EventsProcessed;
    ULONG EventsBlocked;
    ULONG EventsHesitated;
    double GlobalCoherence; // r(t) do K6O
    CLIFFORD_STATE KernelState;
} ARKHE_STATUS, *PARKHE_STATUS;
