import json
import base64
import hashlib
import os
import tempfile

def get_b64_artifacts():
    return {
        "vyupgrade_bridge.py": "aW1wb3J0IG9zCmltcG9ydCBqc29uCmltcG9ydCBoYXNobGliCmltcG9ydCBkYXRldGltZQpmcm9tIHR5cGluZyBpbXBvcnQgRGljdCwgQW55LCBPcHRpb25hbAoKY2xhc3MgVnl1cGdyYWRlQnJpZGdlOgogICAgIiIiCiAgICBNb3RvciBkZSBldm9sdcOnw6NvIHNlZ3VyYSBkZSBjb250cmF0b3MgVnlwZXIuCiAgICBJbnRlZ3Jhw6fDo28gZG8gdnl1cGdyYWRlIGFvIGVjb3NzaXN0ZW1hIEFSS0hFLgogICAgIiIiCiAgICAKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB0YXJnZXRfdmVyc2lvbjogc3RyID0gIjAuNC4zIik6CiAgICAgICAgc2VsZi50YXJnZXRfdmVyc2lvbiA9IHRhcmdldF92ZXJzaW9uCiAgICAgICAgc2VsZi5yZXBvcnRzOiBEaWN0W3N0ciwgQW55XSA9IHt9CiAgICAgICAgCiAgICBkZWYgZ2VuZXJhdGVfemtfcHJvb2Yoc2VsZiwgb3JpZ2luYWxfc291cmNlOiBzdHIsIHJld3JpdHRlbl9zb3VyY2U6IHN0cikgLT4gc3RyOgogICAgICAgICIiIgogICAgICAgIEdlcmEgdW1hIHByb3ZhIFpLIGRlIGVxdWl2YWzDqm5jaWEgY29tcG9ydGFtZW50YWwuCiAgICAgICAgKE1vY2sgcGFyYSBmaW5zIGRlIGNhbm9uaXphw6fDo28pCiAgICAgICAgIiIiCiAgICAgICAgY29tYmluZWQgPSBvcmlnaW5hbF9zb3VyY2UgKyByZXdyaXR0ZW5fc291cmNlCiAgICAgICAgcHJvb2ZfaGFzaCA9IGhhc2hsaWIuc2hhM18yNTYoY29tYmluZWQuZW5jb2RlKCkpLmhleGRpZ2VzdCgpCiAgICAgICAgcmV0dXJuICJ6a19wcm9vZl92eXVwZ3JhZGVfe30iLmZvcm1hdChwcm9vZl9oYXNoKQogICAgICAgIAogICAgZGVmIGFuY2hvcl91cGdyYWRlKHNlbGYsIHVwZ3JhZGVfZGF0YTogRGljdFtzdHIsIEFueV0pIC0+IHN0cjoKICAgICAgICAiIiIKICAgICAgICBBbmNvcmEgbyB1cGdyYWRlIG5hIFRlbXBvcmFsQ2hhaW4gKDkyMykuCiAgICAgICAgIiIiCiAgICAgICAgcGF5bG9hZCA9IGpzb24uZHVtcHModXBncmFkZV9kYXRhLCBzb3J0X2tleXM9VHJ1ZSkuZW5jb2RlKCkKICAgICAgICBhbmNob3JfaGFzaCA9IGhhc2hsaWIuc2hhM18yNTYocGF5bG9hZCkuaGV4ZGlnZXN0KCkKICAgICAgICByZXR1cm4gYW5jaG9yX2hhc2gKICAgICAgICAKICAgIGRlZiBwcm9jZXNzX2NvbnRyYWN0KHNlbGYsIGNvbnRyYWN0X25hbWU6IHN0ciwgc291cmNlOiBzdHIpIC0+IERpY3Rbc3RyLCBBbnldOgogICAgICAgICIiIgogICAgICAgIFByb2Nlc3NhIHVtIGNvbnRyYXRvOiByZWVzY3JldmUsIGdlcmEgcHJvdmEgWksgZSBhbmNvcmEuCiAgICAgICAgIiIiCiAgICAgICAgIyBNb2NrIGRlIHJlZXNjcml0YQogICAgICAgIHJld3JpdHRlbiA9IHNvdXJjZS5yZXBsYWNlKCJ2ZXJzaW9uIDAuMi4xIiwgInZlcnNpb24ge30iLmZvcm1hdChzZWxmLnRhcmdldF92ZXJzaW9uKSkKICAgICAgICAKICAgICAgICB6a19wcm9vZiA9IHNlbGYuZ2VuZXJhdGVfemtfcHJvb2Yoc291cmNlLCByZXdyaXR0ZW4pCiAgICAgICAgCiAgICAgICAgcmVwb3J0ID0gewogICAgICAgICAgICAiY29udHJhY3QiOiBjb250cmFjdF9uYW1lLAogICAgICAgICAgICAidGFyZ2V0X3ZlcnNpb24iOiBzZWxmLnRhcmdldF92ZXJzaW9uLAogICAgICAgICAgICAiemtfcHJvb2YiOiB6a19wcm9vZiwKICAgICAgICAgICAgInRpbWVzdGFtcCI6IGRhdGV0aW1lLmRhdGV0aW1lLnV0Y25vdygpLmlzb2Zvcm1hdCgpLAogICAgICAgICAgICAic3RhdHVzIjogInVwZ3JhZGVkIgogICAgICAgIH0KICAgICAgICAKICAgICAgICBhbmNob3JfaGFzaCA9IHNlbGYuYW5jaG9yX3VwZ3JhZGUocmVwb3J0KQogICAgICAgIHJlcG9ydFsidGVtcG9yYWxfYW5jaG9yIl0gPSBhbmNob3JfaGFzaAogICAgICAgIAogICAgICAgIHNlbGYucmVwb3J0c1tjb250cmFjdF9uYW1lXSA9IHJlcG9ydAogICAgICAgIHJldHVybiByZXBvcnQK"
    }

def compute_seal(payload_dict):
    serialized = json.dumps(payload_dict, sort_keys=True).encode("utf-8")
    return hashlib.sha3_256(serialized).hexdigest()

def main():
    payload = {
        "Substrate": "945",
        "Status": "Canonized",
        "Files": list(get_b64_artifacts().keys())
    }

    seal = compute_seal(payload)
    payload["Canonical_Seal"] = seal

    fd, path = tempfile.mkstemp(suffix=".json", prefix="substrate_945_")
    with os.fdopen(fd, "w") as f:
        json.dump(payload, f, indent=2)

    print("Substrate 945 canonized at:", path)
    print("Seal:", seal)

if __name__ == "__main__":
    main()
