/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StyleInfluenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "artistWorks"
      | "escrowContract"
      | "fingerprints"
      | "influencesExerted"
      | "influencesReceived"
      | "minInfluenceThreshold"
      | "recordBatchInfluence"
      | "recordInfluence"
      | "registerBatch"
      | "registerFingerprint"
      | "setEscrow"
      | "setMinThreshold"
      | "totalFingerprints"
      | "totalInfluences"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowUpdated"
      | "FingerprintRegistered"
      | "InfluenceRecorded"
      | "RoyaltyClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "artistWorks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fingerprints",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "influencesExerted",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "influencesReceived",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minInfluenceThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordBatchInfluence",
    values: [BytesLike[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "recordInfluence",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BytesLike[], BytesLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFingerprint",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFingerprints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalInfluences",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "artistWorks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fingerprints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "influencesExerted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "influencesReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minInfluenceThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordBatchInfluence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordInfluence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFingerprint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFingerprints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInfluences",
    data: BytesLike
  ): Result;
}

export namespace EscrowUpdatedEvent {
  export type InputTuple = [newEscrow: AddressLike];
  export type OutputTuple = [newEscrow: string];
  export interface OutputObject {
    newEscrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FingerprintRegisteredEvent {
  export type InputTuple = [
    fingerprint: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fingerprint: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fingerprint: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InfluenceRecordedEvent {
  export type InputTuple = [
    source: BytesLike,
    target: BytesLike,
    similarity: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    source: string,
    target: string,
    similarity: bigint,
    proofHash: string
  ];
  export interface OutputObject {
    source: string;
    target: string;
    similarity: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoyaltyClaimedEvent {
  export type InputTuple = [
    fingerprint: BytesLike,
    owner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    fingerprint: string,
    owner: string,
    amount: bigint
  ];
  export interface OutputObject {
    fingerprint: string;
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StyleInfluenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StyleInfluenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: StyleInfluenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  artistWorks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  escrowContract: TypedContractMethod<[], [string], "view">;

  fingerprints: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, boolean] & {
        owner: string;
        perceptualHash: string;
        styleHash: string;
        uri: string;
        timestamp: bigint;
        totalInfluence: bigint;
        totalRoyalties: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  influencesExerted: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        sourceFingerprint: string;
        targetFingerprint: string;
        proofHash: string;
        similarity: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  influencesReceived: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        sourceFingerprint: string;
        targetFingerprint: string;
        proofHash: string;
        similarity: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  minInfluenceThreshold: TypedContractMethod<[], [bigint], "view">;

  recordBatchInfluence: TypedContractMethod<
    [sources: BytesLike[], targets: BytesLike[], proofs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  recordInfluence: TypedContractMethod<
    [
      sourceFingerprint: BytesLike,
      targetFingerprint: BytesLike,
      proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registerBatch: TypedContractMethod<
    [perceptualHashes: BytesLike[], styleHashes: BytesLike[], uris: string[]],
    [string[]],
    "nonpayable"
  >;

  registerFingerprint: TypedContractMethod<
    [perceptualHash: BytesLike, styleHash: BytesLike, uri: string],
    [string],
    "nonpayable"
  >;

  setEscrow: TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;

  setMinThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFingerprints: TypedContractMethod<[], [bigint], "view">;

  totalInfluences: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "artistWorks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fingerprints"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, boolean] & {
        owner: string;
        perceptualHash: string;
        styleHash: string;
        uri: string;
        timestamp: bigint;
        totalInfluence: bigint;
        totalRoyalties: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "influencesExerted"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        sourceFingerprint: string;
        targetFingerprint: string;
        proofHash: string;
        similarity: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "influencesReceived"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        sourceFingerprint: string;
        targetFingerprint: string;
        proofHash: string;
        similarity: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "minInfluenceThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordBatchInfluence"
  ): TypedContractMethod<
    [sources: BytesLike[], targets: BytesLike[], proofs: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordInfluence"
  ): TypedContractMethod<
    [
      sourceFingerprint: BytesLike,
      targetFingerprint: BytesLike,
      proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<
    [perceptualHashes: BytesLike[], styleHashes: BytesLike[], uris: string[]],
    [string[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerFingerprint"
  ): TypedContractMethod<
    [perceptualHash: BytesLike, styleHash: BytesLike, uri: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEscrow"
  ): TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFingerprints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalInfluences"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EscrowUpdated"
  ): TypedContractEvent<
    EscrowUpdatedEvent.InputTuple,
    EscrowUpdatedEvent.OutputTuple,
    EscrowUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FingerprintRegistered"
  ): TypedContractEvent<
    FingerprintRegisteredEvent.InputTuple,
    FingerprintRegisteredEvent.OutputTuple,
    FingerprintRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InfluenceRecorded"
  ): TypedContractEvent<
    InfluenceRecordedEvent.InputTuple,
    InfluenceRecordedEvent.OutputTuple,
    InfluenceRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RoyaltyClaimed"
  ): TypedContractEvent<
    RoyaltyClaimedEvent.InputTuple,
    RoyaltyClaimedEvent.OutputTuple,
    RoyaltyClaimedEvent.OutputObject
  >;

  filters: {
    "EscrowUpdated(address)": TypedContractEvent<
      EscrowUpdatedEvent.InputTuple,
      EscrowUpdatedEvent.OutputTuple,
      EscrowUpdatedEvent.OutputObject
    >;
    EscrowUpdated: TypedContractEvent<
      EscrowUpdatedEvent.InputTuple,
      EscrowUpdatedEvent.OutputTuple,
      EscrowUpdatedEvent.OutputObject
    >;

    "FingerprintRegistered(bytes32,address,uint256)": TypedContractEvent<
      FingerprintRegisteredEvent.InputTuple,
      FingerprintRegisteredEvent.OutputTuple,
      FingerprintRegisteredEvent.OutputObject
    >;
    FingerprintRegistered: TypedContractEvent<
      FingerprintRegisteredEvent.InputTuple,
      FingerprintRegisteredEvent.OutputTuple,
      FingerprintRegisteredEvent.OutputObject
    >;

    "InfluenceRecorded(bytes32,bytes32,uint256,bytes32)": TypedContractEvent<
      InfluenceRecordedEvent.InputTuple,
      InfluenceRecordedEvent.OutputTuple,
      InfluenceRecordedEvent.OutputObject
    >;
    InfluenceRecorded: TypedContractEvent<
      InfluenceRecordedEvent.InputTuple,
      InfluenceRecordedEvent.OutputTuple,
      InfluenceRecordedEvent.OutputObject
    >;

    "RoyaltyClaimed(bytes32,address,uint256)": TypedContractEvent<
      RoyaltyClaimedEvent.InputTuple,
      RoyaltyClaimedEvent.OutputTuple,
      RoyaltyClaimedEvent.OutputObject
    >;
    RoyaltyClaimed: TypedContractEvent<
      RoyaltyClaimedEvent.InputTuple,
      RoyaltyClaimedEvent.OutputTuple,
      RoyaltyClaimedEvent.OutputObject
    >;
  };
}
