mkdir -p arkhe_os/starter/shared
mkdir -p arkhe-starter-java-spring/src/main/java/com/arkhe/banking/config
mkdir -p arkhe-starter-java-spring/src/main/java/com/arkhe/banking/controller
mkdir -p arkhe-starter-java-spring/src/main/java/com/arkhe/banking/service
mkdir -p arkhe-starter-java-spring/src/main/java/com/arkhe/banking/model
mkdir -p arkhe-starter-java-spring/src/main/java/com/arkhe/banking/predicate
mkdir -p arkhe-starter-java-spring/src/main/java/com/arkhe/banking/aspect
mkdir -p arkhe-starter-java-spring/src/main/resources/predicates
mkdir -p arkhe-starter-java-spring/src/main/resources/zinc
mkdir -p arkhe-starter-java-spring/src/test/java/com/arkhe/banking/compliance
mkdir -p arkhe-starter-java-spring/src/test/java/com/arkhe/banking/integration
mkdir -p arkhe-starter-java-spring/docker/k8s
mkdir -p arkhe-starter-java-spring/.github/workflows
mkdir -p arkhe-starter-java-spring/scripts

mkdir -p arkhe-starter-python-fastapi/src/arkhe_banking/api/v1/endpoints
mkdir -p arkhe-starter-python-fastapi/src/arkhe_banking/core
mkdir -p arkhe-starter-python-fastapi/src/arkhe_banking/models
mkdir -p arkhe-starter-python-fastapi/src/arkhe_banking/services
mkdir -p arkhe-starter-python-fastapi/src/arkhe_banking/predicates
mkdir -p arkhe-starter-python-fastapi/src/arkhe_banking/utils
mkdir -p arkhe-starter-python-fastapi/tests/unit
mkdir -p arkhe-starter-python-fastapi/tests/integration
mkdir -p arkhe-starter-python-fastapi/docker/k8s
mkdir -p arkhe-starter-python-fastapi/notebooks
mkdir -p arkhe-starter-python-fastapi/.github/workflows
mkdir -p arkhe-starter-python-fastapi/scripts

mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Api/Controllers
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Api/Middleware
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Api/Services
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Api/Models
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Api/Predicates
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Core/Interfaces
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Core/Extensions
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Shared/Models
mkdir -p arkhe-starter-csharp-aspnet/src/Arkhe.Banking.Shared/Utils
mkdir -p arkhe-starter-csharp-aspnet/tests/Arkhe.Banking.Api.Tests/Controllers
mkdir -p arkhe-starter-csharp-aspnet/tests/Arkhe.Banking.Api.Tests/Integration
mkdir -p arkhe-starter-csharp-aspnet/tests/Arkhe.Banking.Core.Tests/Predicates
mkdir -p arkhe-starter-csharp-aspnet/tests/Arkhe.Banking.Core.Tests/Services
mkdir -p arkhe-starter-csharp-aspnet/azure/bicep/modules
mkdir -p arkhe-starter-csharp-aspnet/azure/bicep/parameters
mkdir -p arkhe-starter-csharp-aspnet/azure/pipelines
mkdir -p arkhe-starter-csharp-aspnet/azure/policies
mkdir -p arkhe-starter-csharp-aspnet/docker/k8s
mkdir -p arkhe-starter-csharp-aspnet/scripts

mkdir -p scripts
