// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: oracle.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubstrateId   string                 `protobuf:"bytes,1,opt,name=substrate_id,json=substrateId,proto3" json:"substrate_id,omitempty"`
	Motor         string                 `protobuf:"bytes,2,opt,name=motor,proto3" json:"motor,omitempty"` // e.g., "continental-mind", "qart-engine"
	Gpu           bool                   `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShardRequest) Reset() {
	*x = CreateShardRequest{}
	mi := &file_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShardRequest) ProtoMessage() {}

func (x *CreateShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShardRequest.ProtoReflect.Descriptor instead.
func (*CreateShardRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShardRequest) GetSubstrateId() string {
	if x != nil {
		return x.SubstrateId
	}
	return ""
}

func (x *CreateShardRequest) GetMotor() string {
	if x != nil {
		return x.Motor
	}
	return ""
}

func (x *CreateShardRequest) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *CreateShardRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	SubstrateId   string                 `protobuf:"bytes,2,opt,name=substrate_id,json=substrateId,proto3" json:"substrate_id,omitempty"`
	Motor         string                 `protobuf:"bytes,3,opt,name=motor,proto3" json:"motor,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`     // "provisioning", "running", "dead"
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // gRPC endpoint to the shard itself
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *Shard) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *Shard) GetSubstrateId() string {
	if x != nil {
		return x.SubstrateId
	}
	return ""
}

func (x *Shard) GetMotor() string {
	if x != nil {
		return x.Motor
	}
	return ""
}

func (x *Shard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Shard) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type ListShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsRequest) Reset() {
	*x = ListShardsRequest{}
	mi := &file_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsRequest) ProtoMessage() {}

func (x *ListShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsRequest.ProtoReflect.Descriptor instead.
func (*ListShardsRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{2}
}

type ListShardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shards        []*Shard               `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsResponse) Reset() {
	*x = ListShardsResponse{}
	mi := &file_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsResponse) ProtoMessage() {}

func (x *ListShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsResponse.ProtoReflect.Descriptor instead.
func (*ListShardsResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *ListShardsResponse) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type DestroyShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyShardRequest) Reset() {
	*x = DestroyShardRequest{}
	mi := &file_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyShardRequest) ProtoMessage() {}

func (x *DestroyShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyShardRequest.ProtoReflect.Descriptor instead.
func (*DestroyShardRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type GetShardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardStatusRequest) Reset() {
	*x = GetShardStatusRequest{}
	mi := &file_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardStatusRequest) ProtoMessage() {}

func (x *GetShardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardStatusRequest.ProtoReflect.Descriptor instead.
func (*GetShardStatusRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *GetShardStatusRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStatus) Reset() {
	*x = ShardStatus{}
	mi := &file_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStatus) ProtoMessage() {}

func (x *ShardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStatus.ProtoReflect.Descriptor instead.
func (*ShardStatus) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *ShardStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryRoyaltiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoyaltiesRequest) Reset() {
	*x = QueryRoyaltiesRequest{}
	mi := &file_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoyaltiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoyaltiesRequest) ProtoMessage() {}

func (x *QueryRoyaltiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoyaltiesRequest.ProtoReflect.Descriptor instead.
func (*QueryRoyaltiesRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRoyaltiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Royalty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetBlockId string                 `protobuf:"bytes,1,opt,name=target_block_id,json=targetBlockId,proto3" json:"target_block_id,omitempty"`
	SourceOrcid   string                 `protobuf:"bytes,2,opt,name=source_orcid,json=sourceOrcid,proto3" json:"source_orcid,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Royalty) Reset() {
	*x = Royalty{}
	mi := &file_oracle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Royalty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Royalty) ProtoMessage() {}

func (x *Royalty) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Royalty.ProtoReflect.Descriptor instead.
func (*Royalty) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{8}
}

func (x *Royalty) GetTargetBlockId() string {
	if x != nil {
		return x.TargetBlockId
	}
	return ""
}

func (x *Royalty) GetSourceOrcid() string {
	if x != nil {
		return x.SourceOrcid
	}
	return ""
}

func (x *Royalty) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Royalty) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryRoyaltiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Royalties     []*Royalty             `protobuf:"bytes,1,rep,name=royalties,proto3" json:"royalties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoyaltiesResponse) Reset() {
	*x = QueryRoyaltiesResponse{}
	mi := &file_oracle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoyaltiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoyaltiesResponse) ProtoMessage() {}

func (x *QueryRoyaltiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoyaltiesResponse.ProtoReflect.Descriptor instead.
func (*QueryRoyaltiesResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRoyaltiesResponse) GetRoyalties() []*Royalty {
	if x != nil {
		return x.Royalties
	}
	return nil
}

var File_oracle_proto protoreflect.FileDescriptor

const file_oracle_proto_rawDesc = "" +
	"\n" +
	"\foracle.proto\x12\x05arkhe\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x01\n" +
	"\x12CreateShardRequest\x12!\n" +
	"\fsubstrate_id\x18\x01 \x01(\tR\vsubstrateId\x12\x14\n" +
	"\x05motor\x18\x02 \x01(\tR\x05motor\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\bR\x03gpu\x12=\n" +
	"\x06labels\x18\x04 \x03(\v2%.arkhe.CreateShardRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x05Shard\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12!\n" +
	"\fsubstrate_id\x18\x02 \x01(\tR\vsubstrateId\x12\x14\n" +
	"\x05motor\x18\x03 \x01(\tR\x05motor\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"\x13\n" +
	"\x11ListShardsRequest\":\n" +
	"\x12ListShardsResponse\x12$\n" +
	"\x06shards\x18\x01 \x03(\v2\f.arkhe.ShardR\x06shards\"0\n" +
	"\x13DestroyShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"2\n" +
	"\x15GetShardStatusRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"%\n" +
	"\vShardStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"-\n" +
	"\x15QueryRoyaltiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x84\x01\n" +
	"\aRoyalty\x12&\n" +
	"\x0ftarget_block_id\x18\x01 \x01(\tR\rtargetBlockId\x12!\n" +
	"\fsource_orcid\x18\x02 \x01(\tR\vsourceOrcid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"F\n" +
	"\x16QueryRoyaltiesResponse\x12,\n" +
	"\troyalties\x18\x01 \x03(\v2\x0e.arkhe.RoyaltyR\troyalties2\xe0\x02\n" +
	"\fShardService\x126\n" +
	"\vCreateShard\x12\x19.arkhe.CreateShardRequest\x1a\f.arkhe.Shard\x12A\n" +
	"\n" +
	"ListShards\x12\x18.arkhe.ListShardsRequest\x1a\x19.arkhe.ListShardsResponse\x12B\n" +
	"\fDestroyShard\x12\x1a.arkhe.DestroyShardRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0eGetShardStatus\x12\x1c.arkhe.GetShardStatusRequest\x1a\x12.arkhe.ShardStatus\x12M\n" +
	"\x0eQueryRoyalties\x12\x1c.arkhe.QueryRoyaltiesRequest\x1a\x1d.arkhe.QueryRoyaltiesResponseB\x1fZ\x1dgithub.com/arkhe-os/arkhe/apib\x06proto3"

var (
	file_oracle_proto_rawDescOnce sync.Once
	file_oracle_proto_rawDescData []byte
)

func file_oracle_proto_rawDescGZIP() []byte {
	file_oracle_proto_rawDescOnce.Do(func() {
		file_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)))
	})
	return file_oracle_proto_rawDescData
}

var file_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oracle_proto_goTypes = []any{
	(*CreateShardRequest)(nil),     // 0: arkhe.CreateShardRequest
	(*Shard)(nil),                  // 1: arkhe.Shard
	(*ListShardsRequest)(nil),      // 2: arkhe.ListShardsRequest
	(*ListShardsResponse)(nil),     // 3: arkhe.ListShardsResponse
	(*DestroyShardRequest)(nil),    // 4: arkhe.DestroyShardRequest
	(*GetShardStatusRequest)(nil),  // 5: arkhe.GetShardStatusRequest
	(*ShardStatus)(nil),            // 6: arkhe.ShardStatus
	(*QueryRoyaltiesRequest)(nil),  // 7: arkhe.QueryRoyaltiesRequest
	(*Royalty)(nil),                // 8: arkhe.Royalty
	(*QueryRoyaltiesResponse)(nil), // 9: arkhe.QueryRoyaltiesResponse
	nil,                            // 10: arkhe.CreateShardRequest.LabelsEntry
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_oracle_proto_depIdxs = []int32{
	10, // 0: arkhe.CreateShardRequest.labels:type_name -> arkhe.CreateShardRequest.LabelsEntry
	1,  // 1: arkhe.ListShardsResponse.shards:type_name -> arkhe.Shard
	8,  // 2: arkhe.QueryRoyaltiesResponse.royalties:type_name -> arkhe.Royalty
	0,  // 3: arkhe.ShardService.CreateShard:input_type -> arkhe.CreateShardRequest
	2,  // 4: arkhe.ShardService.ListShards:input_type -> arkhe.ListShardsRequest
	4,  // 5: arkhe.ShardService.DestroyShard:input_type -> arkhe.DestroyShardRequest
	5,  // 6: arkhe.ShardService.GetShardStatus:input_type -> arkhe.GetShardStatusRequest
	7,  // 7: arkhe.ShardService.QueryRoyalties:input_type -> arkhe.QueryRoyaltiesRequest
	1,  // 8: arkhe.ShardService.CreateShard:output_type -> arkhe.Shard
	3,  // 9: arkhe.ShardService.ListShards:output_type -> arkhe.ListShardsResponse
	11, // 10: arkhe.ShardService.DestroyShard:output_type -> google.protobuf.Empty
	6,  // 11: arkhe.ShardService.GetShardStatus:output_type -> arkhe.ShardStatus
	9,  // 12: arkhe.ShardService.QueryRoyalties:output_type -> arkhe.QueryRoyaltiesResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_oracle_proto_init() }
func file_oracle_proto_init() {
	if File_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oracle_proto_goTypes,
		DependencyIndexes: file_oracle_proto_depIdxs,
		MessageInfos:      file_oracle_proto_msgTypes,
	}.Build()
	File_oracle_proto = out.File
	file_oracle_proto_goTypes = nil
	file_oracle_proto_depIdxs = nil
}
