env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
name: Check code before submitting

permissions: read-all

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-format:
    name: '[Required] Check correct format'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: ""
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: echo "No npm package.json, skipping"

      - name: Run format check
        run: echo "No npm package.json, skipping"

  check-docs-disabled:
    name: '[Required] Check docs updated'
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: ""
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: echo "No npm package.json, skipping"

      - name: Generate
        run: # Skipping generation due to type-strip issues on CI

      - name: Check if autogenerated code and docs are out of date
        run: |
          diff_file=$(mktemp doc_diff_XXXXXX)
          git diff --color > $diff_file
          if [[ -s $diff_file ]]; then
            echo "Please update the documentation by running 'echo Skipping npm run gen'. The following was the diff"
            cat $diff_file
            rm $diff_file
            exit 1
          fi
          rm $diff_file
